---
title: "About Page"
author: "Hamid Khan"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

Hello! Welcome to my final project for GOV - 1005, where I analyze granular data on over a thousand cricket matches to glean interesting insights about the leading cricketers and their teams. 

I chose to focus my analysis on cricket because I am from Pakistan and have been an avid follower of the sport for over a decade. In college, I find it hard to follow the game as much as I would like to, so this project is a way for me to further explore and contribute to cricket, a sport that is an important part of my life. 


## Data

The primary data source used in this project is from [cricsheet.org](cricsheet.org). The website has compiled ball-by-ball data on over 5000 cricket matches. The cricket data is grouped according to gender and then further divided based on the match format. In this project, I used the yaml files for the following two match types: 

i) [One Day Internationals](https://cricsheet.org/downloads/odis_male.zip)

ii) [T20 Internationals](https://cricsheet.org/downloads/t20s_male.zip)

Using the [yorkr](https://cran.r-project.org/web/packages/yorkr/yorkr.pdf) package, I first converted the yaml files that contained the commentary data into .RData files. I then compiled the separate RData files into two seperate meta-datasets, one for each format.The [first](https://github.com/hak7980/Final-Project---GOV---1005/blob/master/raw-data/odimetadata.RData) of there contains information on 1298 One Day Internationals and the [second](https://github.com/hak7980/Final-Project---GOV---1005/blob/master/raw-data/t20metadata.RData) contains information on 528 T20 Internationals. 

All the data analysis is conducted using information from these two datasets. 


Github repo: https://github.com/hak7980/Final-Project---GOV---1005.git

